services:
  - type: web
    name: ai-video-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: IMAGINE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: KLING_ACCESS_KEY
        sync: false
      - key: KLING_SECRET_KEY
        sync: false